// Wrestling Card Definitions
// Folkstyle: USA Wrestling folkstyle curriculum - NFHS rules
// Freestyle: UWW international freestyle rules
// Greco-Roman: UWW Greco-Roman rules - no holds below the hips

export const POSITIONS = {
  NEUTRAL: 'neutral',
  TOP: 'top',
  BOTTOM: 'bottom',
};

export const CONDITIONS = {
  BROKEN_DOWN: 'broken_down',
  CONTROL_ESTABLISHED: 'control_established',
  TOP_PRESSURE: 'top_pressure',
  FRONT_HEADLOCK_CONTROL: 'front_headlock_control',
  FRONT_HEADLOCK_TRAPPED: 'front_headlock_trapped', // Defender being held in the front headlock
  RECOVERING: 'recovering',
  GOOD_BASE: 'good_base',             // Bottom wrestler built a solid base by surviving turn attempts
  HAND_FIGHTING: 'hand_fighting_control', // Neutral wrestler winning the hand-fighting battle
  INSIDE_POSITION: 'inside_position',     // Greco: underhook advantage - powers up throws
  LEG_ATTACK_SECURED: 'leg_attack_secured',   // Attacker has a leg - needs to finish the takedown
  LEG_ATTACK_TRAPPED: 'leg_attack_trapped',   // Defender's leg is caught - needs to free it
  SCRAMBLE: 'scramble',                       // Both wrestlers tangled in a scramble
  TIE_UP: 'tie_up',                           // Neutral tie-up established - unlocks chain attacks
  REAR_STANDING: 'rear_standing',             // Attacker behind opponent standing - needs mat return to finish
  REAR_STANDING_TRAPPED: 'rear_standing_trapped', // Defender has someone behind them - must fight the rear position
  BASE_BUILT: 'base_built',                   // Bottom wrestler built a base - unlocks stand-up escape
  LEG_RIDE_ESTABLISHED: 'leg_ride_established', // Top wrestler has legs hooked inside opponent's - unlocks leg-ride chain (folkstyle)
};

// Style-aware scoring - engine resolves points via getScores(style) at runtime
export const SCORES = {
  folkstyle: {
    TAKEDOWN: 3,
    ESCAPE: 1,
    REVERSAL: 2,
    NEAR_FALL_2: 2,
    NEAR_FALL_3: 3,
    NEAR_FALL_4: 4,
    // Phase 3 - Referee Calls. Stalling warnings 1 & 2 are free; the
    // 3rd warning awards +1 to the opponent. Resolved in the engine's
    // checkStalling() helper.
    STALLING_PENALTY: 1,
  },
  freestyle: {
    TAKEDOWN: 2,
    ESCAPE: 1,
    REVERSAL: 1,
    EXPOSURE: 2,
    GRAND_AMPLITUDE: 5,
    PASSIVITY: 1,
    // Freestyle still uses near_fall types for shared turn cards
    NEAR_FALL_2: 2,
    NEAR_FALL_3: 2,
    NEAR_FALL_4: 2,
  },
  greco: {
    TAKEDOWN: 2,
    ESCAPE: 1,
    REVERSAL: 1,
    EXPOSURE: 2,
    GRAND_AMPLITUDE: 5,
    PASSIVITY: 1,
    NEAR_FALL_2: 2,
    NEAR_FALL_3: 2,
    NEAR_FALL_4: 2,
  },
  // Women's freestyle uses the identical UWW freestyle scoring engine. Kept
  // as its own entry so future divergences (NCAA Women's tweaks, NFHS girls
  // overrides) have a clean home.
  womens_freestyle: {
    TAKEDOWN: 2,
    ESCAPE: 1,
    REVERSAL: 1,
    EXPOSURE: 2,
    GRAND_AMPLITUDE: 5,
    PASSIVITY: 1,
    NEAR_FALL_2: 2,
    NEAR_FALL_3: 2,
    NEAR_FALL_4: 2,
  },
};

export function getScores(style) {
  return SCORES[style] || SCORES.folkstyle;
}

// ─── CARD LIBRARY ─────────────────────────────────────────────────────────────

export const CARDS = {

  // ══ NEUTRAL OFFENSE ══════════════════════════════════════════════════════════

  double_leg: {
    id: 'double_leg',
    name: 'Double Leg',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 72,
    description: 'Blast through both legs for a takedown',
    counters: ['sprawl', 'front_headlock'],
    setupRequired: [],
    scoreEffect: { type: 'takedown' },
    flavor: 'Level change and drive!',
    styles: ['folkstyle', 'freestyle'],
  },
  single_leg: {
    id: 'single_leg',
    name: 'Single Leg',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 68,
    description: 'Attack one leg and drive through for takedown',
    counters: ['sprawl', 'whizzer'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.LEG_ATTACK_SECURED },
    flavor: 'Drive through the hips!',
    styles: ['folkstyle', 'freestyle'],
  },
  high_crotch: {
    id: 'high_crotch',
    name: 'High Crotch',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 70,
    description: 'Step inside, secure the leg high on the thigh',
    counters: ['sprawl', 'whizzer'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.LEG_ATTACK_SECURED },
    flavor: 'Inside position is everything.',
    styles: ['folkstyle', 'freestyle'],
  },
  sweep_single: {
    id: 'sweep_single',
    name: 'Sweep Single',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 62,
    description: 'Sweep the lead leg from the outside',
    counters: ['whizzer', 'sprawl'],
    setupRequired: [],
    scoreEffect: { type: 'takedown' },
    flavor: 'Sweep and finish!',
    styles: ['folkstyle', 'freestyle'],
  },
  duck_under: {
    id: 'duck_under',
    name: 'Duck Under',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 63,
    description: 'Duck beneath an arm to get behind - finish with a mat return',
    counters: ['whizzer'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.REAR_STANDING },
    flavor: 'Under the arm and behind!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  snap_spin: {
    id: 'snap_spin',
    name: 'Snap and Spin',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 70,
    description: 'Snap head down and spin to the back',
    counters: ['re_shot', 'peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'takedown' },
    flavor: 'Control the head, spin behind!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  go_behind: {
    id: 'go_behind',
    name: 'Go Behind',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 66,
    description: 'Secure body lock from behind - finish with a mat return',
    counters: [],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.REAR_STANDING },
    flavor: 'Secure the waist, own the match.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fireman_carry: {
    id: 'fireman_carry',
    name: "Fireman's Carry",
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 70,
    description: 'Duck under, load the arm and leg, carry through',
    counters: ['sprawl'],
    setupRequired: [],
    scoreEffect: { type: 'takedown' },
    flavor: 'Lift and carry through!',
    styles: ['folkstyle', 'freestyle'],
  },
  arm_drag: {
    id: 'arm_drag',
    name: 'Arm Drag',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 60,
    description: 'Redirect the arm to get behind - finish with a mat return',
    counters: ['whizzer'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.REAR_STANDING },
    flavor: 'Pull the arm, get behind.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  // Russian tie - 2-on-1 control on a single arm. Foundational international
  // hand-fighting position; angles the opponent's shoulder away and opens
  // single leg, hi-C, and throw-by attacks. Sets TIE_UP so it chains.
  russian_tie: {
    id: 'russian_tie',
    name: 'Russian Tie',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 56,
    description: 'Two-on-one wrist + tricep control - opens chain attacks',
    counters: ['peek_out', 'hand_fight_snap'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.TIE_UP },
    flavor: 'Wrist and tricep - own the arm.',
    styles: ['freestyle', 'greco', 'womens_freestyle'],
  },
  // Ankle pick - quick-score from a tie-up or underhook. Reach down,
  // snatch the back of the near ankle while pushing the upper body the
  // other way. A women's wrestling staple.
  ankle_pick: {
    id: 'ankle_pick',
    name: 'Ankle Pick',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Snatch the ankle while redirecting the upper body',
    counters: ['sprawl', 'down_block'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Pick the ankle, push the head.',
    styles: ['freestyle', 'womens_freestyle'],
  },

  // ══ LEG ATTACK FINISHERS (require LEG_ATTACK_SECURED) ════════════════════════

  run_the_pipe: {
    id: 'run_the_pipe',
    name: 'Run the Pipe',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 78,
    description: 'Drive through the single leg - run the pipe to finish',
    counters: [],
    setupRequired: [CONDITIONS.LEG_ATTACK_SECURED],
    scoreEffect: { type: 'takedown' },
    flavor: 'Keep driving through!',
    styles: ['folkstyle', 'freestyle'],
  },
  elevate_and_trip: {
    id: 'elevate_and_trip',
    name: 'Elevate & Trip',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 70,
    description: 'Lift the captured leg and trip the base leg',
    counters: [],
    setupRequired: [CONDITIONS.LEG_ATTACK_SECURED],
    scoreEffect: { type: 'takedown' },
    flavor: 'Elevate high, trip the base!',
    styles: ['folkstyle', 'freestyle'],
  },
  mat_return_from_leg: {
    id: 'mat_return_from_leg',
    name: 'Mat Return (Leg)',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 68,
    description: 'Pull the leg tight and return opponent to the mat',
    counters: [],
    setupRequired: [CONDITIONS.LEG_ATTACK_SECURED],
    scoreEffect: { type: 'takedown' },
    flavor: 'Bring them down to the mat!',
    styles: ['folkstyle', 'freestyle'],
  },

  // ══ LEG ATTACK DEFENSE (require LEG_ATTACK_TRAPPED) ═════════════════════════

  limp_leg: {
    id: 'limp_leg',
    name: 'Limp Leg',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 78,
    description: 'Go limp on the captured leg to slip free',
    counters: [],
    strongAgainst: ['run_the_pipe', 'mat_return_from_leg'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.SCRAMBLE },
    flavor: 'Dead weight the leg, slip free!',
    styles: ['folkstyle', 'freestyle'],
  },
  whizzer_hop: {
    id: 'whizzer_hop',
    name: 'Whizzer & Hop',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 80,
    description: 'Overhook and hop away to free the leg',
    counters: [],
    strongAgainst: ['run_the_pipe', 'elevate_and_trip'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.SCRAMBLE },
    flavor: 'Whizzer in and hop free!',
    styles: ['folkstyle', 'freestyle'],
  },
  crossface_and_circle: {
    id: 'crossface_and_circle',
    name: 'Crossface & Circle',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 74,
    description: 'Push the face and circle away to free the leg',
    counters: [],
    strongAgainst: ['elevate_and_trip', 'mat_return_from_leg'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.SCRAMBLE },
    flavor: 'Crossface and get free!',
    styles: ['folkstyle', 'freestyle'],
  },
  front_headlock_counter: {
    id: 'front_headlock_counter',
    name: 'FHL Counter',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 76,
    description: 'Snap to a front headlock as they shoot in - neutralize the leg, take control',
    counters: [],
    strongAgainst: ['mat_return_from_leg'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.FRONT_HEADLOCK_CONTROL },
    flavor: 'Snap them down, take the head!',
    styles: ['folkstyle', 'freestyle'],
  },
  whizzer_lateral_drop: {
    id: 'whizzer_lateral_drop',
    name: 'Whizzer Drop',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 80,
    description: 'Overhook the trapping arm, hip-throw them past you for a takedown',
    counters: [],
    strongAgainst: ['elevate_and_trip'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'takedown' },
    flavor: 'Whizzer in - throw them past!',
    styles: ['folkstyle', 'freestyle'],
  },
  heavy_hips: {
    id: 'heavy_hips',
    name: 'Heavy Hips',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 76,
    description: 'Drop your weight onto the leg - deny the drive and slip free',
    counters: [],
    strongAgainst: ['run_the_pipe'],
    setupRequired: [],
    legDefense: true,
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.SCRAMBLE },
    flavor: 'Heavy hips - immovable.',
    styles: ['folkstyle', 'freestyle'],
  },
  // ══ NEUTRAL COUNTERS ═════════════════════════════════════════════════════════

  sprawl: {
    id: 'sprawl',
    name: 'Sprawl',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 65,
    description: 'Shoot hips back and sprawl to stuff the shot',
    counters: [],
    // strongAgainst: cards this move specifically beats (used for +22 counter bonus in computePower)
    strongAgainst: ['double_leg', 'single_leg', 'high_crotch', 'sweep_single', 'fireman_carry'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.FRONT_HEADLOCK_CONTROL },
    flavor: 'Hips back, head up!',
    styles: ['folkstyle', 'freestyle'],
  },
  whizzer: {
    id: 'whizzer',
    name: 'Whizzer',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 65,
    description: 'Overhook arm to redirect and counter single legs',
    counters: [],
    strongAgainst: ['single_leg', 'high_crotch', 'sweep_single', 'duck_under', 'arm_drag'],
    setupRequired: [],
    scoreEffect: { type: 'counter' },
    flavor: 'Block the arm, stay on top.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  front_headlock: {
    id: 'front_headlock',
    name: 'Front Headlock',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 54,
    description: 'Snap and lock head and arm for control',
    counters: [],
    strongAgainst: ['double_leg', 'fireman_carry', 'snap_spin', 'duck_under'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.FRONT_HEADLOCK_CONTROL },
    flavor: 'Snap and lock the head.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ── FRONT HEADLOCK BRANCH MOVES ───────────────────────────────────────────
  // All require FRONT_HEADLOCK_CONTROL - these form a true branching position

  fhl_go_behind: {
    id: 'fhl_go_behind',
    name: 'FHL → Go Behind',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 78,
    description: 'From front headlock - spin to the back for takedown',
    counters: [],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown' },
    flavor: 'Spin out the back door!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_knee_tap: {
    id: 'fhl_knee_tap',
    name: 'FHL → Knee Tap',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 64,
    description: 'FHL: reach through, tap knee for takedown',
    counters: [],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown' },
    flavor: 'Tap the knee, finish low.',
    styles: ['folkstyle', 'freestyle'],
  },
  fhl_whipover: {
    id: 'fhl_whipover',
    name: 'FHL → Whipover',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 68,
    description: 'From front headlock - whip opponent over for takedown',
    counters: [],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown' },
    flavor: 'Whip them over - finish!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_cement_mixer: {
    id: 'fhl_cement_mixer',
    name: 'Cement Mixer',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 64,
    description: 'FHL: spin arm and roll - takedown or near fall',
    counters: [],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown' },
    flavor: 'Roll it through!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_gator_roll: {
    id: 'fhl_gator_roll',
    name: 'FHL → Gator Roll',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 58,
    description: 'FHL: roll opponent to the mat for near fall',
    counters: [],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown_near_fall', pinChance: 0.12 },
    flavor: 'Barrel roll - put them on their back!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_snap_spin: {
    id: 'fhl_snap_spin',
    name: 'FHL → Snap & Spin',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 67,
    description: 'FHL: snap the head, spin behind for takedown',
    counters: [],
    strongAgainst: ['peek_out'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_CONTROL],
    scoreEffect: { type: 'takedown' },
    flavor: 'Snap, spin, take the back!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ── FHL DEFENSE (trapped in front headlock) ───────────────────────────────
  // These cards are ONLY available to the player being held in a front headlock
  // (setupRequired: FRONT_HEADLOCK_TRAPPED). Generic attacks are restricted while trapped.

  fhl_body_dump: {
    id: 'fhl_body_dump',
    name: 'Body Dump',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    fhlDefense: true,
    staminaCost: 8,
    basePower: 68,
    description: 'Drive hips forward and dump them over - scramble free',
    counters: [],
    strongAgainst: ['fhl_whipover', 'fhl_cement_mixer'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Drive the hips - use their control against them!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_snap_back: {
    id: 'fhl_snap_back',
    name: 'Snap Back',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    fhlDefense: true,
    staminaCost: 5,
    basePower: 74,
    description: 'Snap head back and circle free to reset',
    counters: [],
    strongAgainst: ['fhl_snap_spin', 'fhl_go_behind'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Head back, step out - neutralize.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_inside_step: {
    id: 'fhl_inside_step',
    name: 'Inside Step',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    fhlDefense: true,
    staminaCost: 6,
    basePower: 72,
    description: 'Step inside, post the hip, take the angle away',
    counters: [],
    strongAgainst: ['fhl_knee_tap', 'fhl_go_behind'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_TRAPPED],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.HAND_FIGHTING },
    flavor: 'Step inside. Take the hip away.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_sit_through: {
    id: 'fhl_sit_through',
    name: 'Sit-Through',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    fhlDefense: true,
    staminaCost: 6,
    basePower: 70,
    description: 'Drop to a hip and sit through - escape to the side',
    counters: [],
    strongAgainst: ['fhl_go_behind', 'fhl_knee_tap'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Hip down, sit through - they are gone.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  fhl_stand_up: {
    id: 'fhl_stand_up',
    name: 'Stand Up',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    fhlDefense: true,
    staminaCost: 7,
    basePower: 66,
    description: 'Power up to base and fight back to standing',
    counters: [],
    strongAgainst: ['fhl_whipover', 'fhl_snap_spin'],
    setupRequired: [CONDITIONS.FRONT_HEADLOCK_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Drive up - back to neutral.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ REAR STANDING DEFENSE (require REAR_STANDING_TRAPPED) ════════════════════
  // Defender has someone behind them in a rear standing / rear body lock. These
  // are the legitimate responses; the trapped defender's hand is restricted to
  // this pool (mirror of the FHL / leg-attack trapped pools). The 3 counter/
  // scramble cards are legal in all styles; the reversal and escape cards are
  // folkstyle-only - international styles do not score rear standing the same
  // way, so escape/reversal scoring frequency is not added to Greco/freestyle.
  rear_hand_fight: {
    id: 'rear_hand_fight',
    name: 'Hand Fight Free',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    rearDefense: true,
    staminaCost: 6,
    basePower: 76,
    description: 'Peel the locked hands apart and break to a scramble',
    counters: [],
    strongAgainst: ['rear_lift', 'rear_mat_return'],
    setupRequired: [CONDITIONS.REAR_STANDING_TRAPPED],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.SCRAMBLE },
    flavor: 'Break the grip - nobody finishes from there.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  rear_hip_down: {
    id: 'rear_hip_down',
    name: 'Sit to the Hips',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    rearDefense: true,
    staminaCost: 5,
    basePower: 78,
    description: 'Lower the hips and base out - deny the lift and the return',
    counters: [],
    strongAgainst: ['rear_lift', 'rear_trip'],
    setupRequired: [CONDITIONS.REAR_STANDING_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Hips down, weight down - they cannot lift you.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  rear_whizzer_block: {
    id: 'rear_whizzer_block',
    name: 'Whizzer Block',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    rearDefense: true,
    staminaCost: 7,
    basePower: 76,
    description: 'Overhook the lifting arm and block the mat return',
    counters: [],
    strongAgainst: ['rear_mat_return', 'rear_lift'],
    setupRequired: [CONDITIONS.REAR_STANDING_TRAPPED],
    scoreEffect: { type: 'counter' },
    flavor: 'Trap the arm - the return goes nowhere.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  rear_standing_switch: {
    id: 'rear_standing_switch',
    name: 'Standing Switch',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    rearDefense: true,
    staminaCost: 8,
    basePower: 74,
    description: 'Turn back through and come around behind the attacker',
    counters: [],
    strongAgainst: ['rear_trip', 'rear_mat_return'],
    setupRequired: [CONDITIONS.REAR_STANDING_TRAPPED],
    scoreEffect: { type: 'reversal' },
    flavor: 'Switch back - now you are the one behind.',
    styles: ['folkstyle'],
  },
  rear_peel_and_turn: {
    id: 'rear_peel_and_turn',
    name: 'Peel & Turn In',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    rearDefense: true,
    staminaCost: 6,
    basePower: 78,
    description: 'Peel the hands, turn in and face the opponent - escape free',
    counters: [],
    strongAgainst: ['rear_trip', 'rear_mat_return'],
    setupRequired: [CONDITIONS.REAR_STANDING_TRAPPED],
    scoreEffect: { type: 'escape' },
    flavor: 'Peel and face them - back to even.',
    styles: ['folkstyle'],
  },

  re_shot: {
    id: 're_shot',
    name: 'Re-Shot',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 63,
    description: 'Counter-attack with an immediate shot',
    counters: [],
    strongAgainst: ['snap_spin', 'go_behind'],
    setupRequired: [],
    scoreEffect: { type: 'takedown' },
    flavor: 'Beat them to the shot!',
    styles: ['folkstyle', 'freestyle'],
  },
  down_block: {
    id: 'down_block',
    name: 'Down Block',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 58,
    description: 'Block the attack with a downward arm motion',
    counters: [],
    strongAgainst: ['double_leg', 'high_crotch'],
    setupRequired: [],
    scoreEffect: { type: 'counter' },
    flavor: 'Keep the hips away.',
    styles: ['folkstyle', 'freestyle'],
  },
  stuff_head: {
    id: 'stuff_head',
    name: 'Stuff the Head',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 62,
    description: 'Push the head down to neutralize the attack',
    counters: [],
    strongAgainst: ['double_leg', 'single_leg', 'high_crotch'],
    setupRequired: [],
    scoreEffect: { type: 'counter' },
    flavor: 'Stuff it down!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  peek_out: {
    id: 'peek_out',
    name: 'Peek Out',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 60,
    description: 'Peel head out of FHL or tie-up to escape',
    counters: [],
    strongAgainst: [
      'snap_spin', 'go_behind', 'arm_drag', 'front_headlock',
      'fhl_go_behind', 'fhl_knee_tap', 'fhl_whipover', 'fhl_cement_mixer', 'fhl_gator_roll', 'fhl_snap_spin',
      'collar_tie', 'underhook_control', 'snap_down',
    ],
    setupRequired: [],
    scoreEffect: { type: 'counter' },
    flavor: 'Slip the head - neutralize the control.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ GRAND AMPLITUDE THROWS (Freestyle only) ═════════════════════════════════

  suplex: {
    id: 'suplex',
    name: 'Suplex',
    category: 'throw',
    position: POSITIONS.NEUTRAL,
    staminaCost: 12,
    basePower: 68,
    description: 'Lock the body, arch and throw for back exposure',
    counters: ['sprawl', 'whizzer'],
    strongAgainst: ['down_block', 'stuff_head', 'peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'grand_amplitude', pinChance: 0.15 },
    flavor: 'Arch and throw - feet to back!',
    styles: ['freestyle', 'greco'],
  },
  headlock_throw: {
    id: 'headlock_throw',
    name: 'Headlock',
    category: 'throw',
    position: POSITIONS.NEUTRAL,
    staminaCost: 11,
    basePower: 76,
    description: 'Lock the head, step across, drive to the back',
    counters: ['whizzer', 'sprawl'],
    strongAgainst: ['down_block', 'stuff_head'],
    setupRequired: [],
    scoreEffect: { type: 'grand_amplitude', pinChance: 0.13 },
    flavor: 'Lock the head, throw for the fall!',
    styles: ['freestyle', 'greco'],
  },
  lateral_drop: {
    id: 'lateral_drop',
    name: 'Lateral Drop',
    category: 'throw',
    position: POSITIONS.NEUTRAL,
    staminaCost: 11,
    basePower: 74,
    description: 'Over-under grip, drop to the side for exposure',
    counters: ['whizzer'],
    strongAgainst: ['stuff_head', 'peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'grand_amplitude', pinChance: 0.12 },
    flavor: 'Drop and expose the back!',
    styles: ['freestyle', 'greco'],
  },
  bear_hug_lift: {
    id: 'bear_hug_lift',
    name: 'Bear Hug Lift',
    category: 'throw',
    position: POSITIONS.NEUTRAL,
    staminaCost: 13,
    basePower: 80,
    description: 'Lock the body, squeeze and lift off the mat',
    counters: ['sprawl', 'whizzer'],
    strongAgainst: ['down_block', 'stuff_head', 'peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'grand_amplitude', pinChance: 0.16 },
    flavor: 'Squeeze and lift - maximum amplitude!',
    styles: ['freestyle', 'greco'],
  },

  // ══ GRECO-ROMAN NEUTRAL (Greco only) ═════════════════════════════════════════

  pummel_inside: {
    id: 'pummel_inside',
    name: 'Pummel Inside',
    category: 'transition',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 62,
    description: 'Fight for underhooks - win inside position to set up throws',
    counters: [],
    strongAgainst: ['stuff_head', 'peek_out', 'whizzer'],
    setupRequired: [],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.INSIDE_POSITION },
    flavor: 'Pummel, pummel - own the inside.',
    styles: ['greco'],
  },
  arm_throw: {
    id: 'arm_throw',
    name: 'Arm Throw',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 48,
    description: 'Grip arm, step under, rotate for takedown',
    counters: ['whizzer'],
    strongAgainst: ['stuff_head', 'peek_out'],
    setupRequired: [CONDITIONS.INSIDE_POSITION],
    scoreEffect: { type: 'takedown' },
    flavor: 'Pull the arm, step under - throw!',
    styles: ['greco'],
  },
  shuck_by: {
    id: 'shuck_by',
    name: 'Shuck-By',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 50,
    description: 'Redirect arm past you, spin to the back for body lock',
    counters: ['whizzer'],
    strongAgainst: ['pummel_inside', 'stuff_head'],
    setupRequired: [CONDITIONS.INSIDE_POSITION],
    scoreEffect: { type: 'takedown' },
    flavor: 'Shuck the arm, take the back.',
    styles: ['greco'],
  },

  // ══ GRECO-ROMAN PAR TERRE TOP (Greco only) ═════════════════════════════════

  reverse_lift: {
    id: 'reverse_lift',
    name: 'Reverse Lift',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 14,
    basePower: 66,
    description: 'Lock waist from behind, lift and arch to back',
    counters: ['stand_up'],
    strongAgainst: ['base_build', 'short_sit', 'head_post'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'grand_amplitude', pinChance: 0.30 },
    flavor: 'Lift them off the mat - maximum amplitude!',
    styles: ['greco'],
  },
  arm_drag_to_gut_wrench: {
    id: 'arm_drag_to_gut_wrench',
    name: 'Arm Drag → Gut Wrench',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 70,
    description: 'Arm drag to remove the post, cinch gut wrench',
    counters: ['hip_heist'],
    strongAgainst: ['hand_control_escape', 'base_build'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'exposure', pinChance: 0.12 },
    flavor: 'Drag the arm, lock the gut - turn and score!',
    styles: ['greco'],
  },

  // ══ GRECO-ROMAN BOTTOM DEFENSE (Greco only) ════════════════════════════════

  bridge_defense: {
    id: 'bridge_defense',
    name: 'Bridge Defense',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 5,
    basePower: 80,
    description: 'Bridge hard against the rotation - fight the gut wrench',
    counters: ['spiral_ride'],
    strongAgainst: ['gut_wrench', 'arm_drag_to_gut_wrench', 'tilt', 'far_side_tilt'],
    setupRequired: [],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Bridge against the turn - survive!',
    styles: ['greco'],
  },

  // ══ TOP CONTROL ══════════════════════════════════════════════════════════════

  spiral_ride: {
    id: 'spiral_ride',
    name: 'Spiral Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 66,
    description: 'Spiral the arm and drive to break the base',
    counters: ['stand_up', 'switch_move'],
    strongAgainst: ['stand_up', 'switch_move'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Spiral down, flatten them out.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  ankle_ride: {
    id: 'ankle_ride',
    name: 'Ankle Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 62,
    description: 'Hook the far ankle to shut down movement',
    counters: ['stand_up'],
    strongAgainst: ['stand_up'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.CONTROL_ESTABLISHED },
    flavor: 'Lock the ankle, lock the match.',
    styles: ['folkstyle'],
  },
  tight_waist: {
    id: 'tight_waist',
    name: 'Tight Waist',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 61,
    description: 'Cinch the waist tight and apply heavy pressure',
    counters: ['switch_move', 'hip_heist'],
    strongAgainst: ['sit_out', 'hip_heist'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.TOP_PRESSURE },
    flavor: 'Lock the waist tight.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  pop_chop: {
    id: 'pop_chop',
    name: 'Pop and Chop',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 4,
    basePower: 59,
    description: 'Pop the elbow, chop the arm to flatten',
    counters: ['stand_up'],
    strongAgainst: ['stand_up', 'base_build'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Pop and chop the arm.',
    styles: ['folkstyle'],
  },
  mat_return: {
    id: 'mat_return',
    name: 'Mat Return',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 75,
    description: 'Drive them back to the mat from their feet',
    counters: ['switch_move'],
    strongAgainst: ['stand_up', 'tripod_stand'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Put them back on the mat.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  claw_ride: {
    id: 'claw_ride',
    name: 'Claw Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 63,
    description: 'Claw the far ankle to lock down the hips',
    counters: ['hip_heist'],
    strongAgainst: ['hip_heist', 'granby_roll'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.TOP_PRESSURE },
    flavor: 'Clamp the ankle, control the hips.',
    // Ankle hold = below-waist contact, illegal in Greco-Roman.
    styles: ['folkstyle', 'freestyle'],
  },
  cross_face_pressure: {
    id: 'cross_face_pressure',
    name: 'Cross-Face',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 72,
    description: 'Drive the forearm across the jaw to flatten',
    counters: ['granby_roll', 'sit_out'],
    strongAgainst: ['sit_out'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Forearm across the face!',
    styles: ['folkstyle', 'freestyle'],
  },
  cross_wrist_ride: {
    id: 'cross_wrist_ride',
    name: 'Cross-Wrist Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 63,
    description: 'Trap the far wrist across the body',
    counters: ['hand_control_escape'],
    strongAgainst: ['hand_control_escape'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.CONTROL_ESTABLISHED },
    flavor: 'Lock the wrist, own the position.',
    styles: ['folkstyle'],
  },
  chop_and_drive: {
    id: 'chop_and_drive',
    name: 'Chop & Drive',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 65,
    description: 'Chop the arm and drive opponent flat to the mat',
    counters: ['hip_heist', 'sit_out'],
    strongAgainst: ['base_build', 'head_post'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Chop and flatten!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ PAR TERRE TOP (Freestyle only) ══════════════════════════════════════════

  gut_wrench: {
    id: 'gut_wrench',
    name: 'Gut Wrench',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 7,
    basePower: 70,
    description: 'Lock waist, rotate for back exposure',
    counters: ['stand_up', 'switch_move'],
    strongAgainst: ['base_build', 'short_sit'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'exposure', pinChance: 0.10 },
    flavor: 'Lock the gut, turn and score!',
    styles: ['freestyle', 'greco'],
  },
  leg_lace: {
    id: 'leg_lace',
    name: 'Leg Lace',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 7,
    basePower: 66,
    description: 'Figure-4 both legs, roll for back exposure',
    counters: ['hip_heist'],
    strongAgainst: ['base_build', 'short_sit', 'head_post'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'exposure', pinChance: 0.08 },
    flavor: 'Lace the legs, roll and expose!',
    styles: ['freestyle'],
  },
  step_over: {
    id: 'step_over',
    name: 'Step-Over',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 64,
    description: 'Step foot over arm or leg, rotate for back exposure',
    counters: ['granby_roll'],
    strongAgainst: ['short_sit'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'exposure', pinChance: 0.06 },
    flavor: 'Step over, expose the back!',
    styles: ['freestyle'],
  },
  // Women's freestyle signature: gut wrench chained directly into a leg
  // lace. Per the 2024 European Championships par-terre breakdown, this
  // combo is more central to elite women's wrestling than to men's. Higher
  // base power than either move alone, but only available right after a
  // gut wrench scored (combo precondition).
  gut_wrench_to_leg_lace: {
    id: 'gut_wrench_to_leg_lace',
    name: 'Gut Wrench to Leg Lace',
    category: 'par_terre_top',
    position: POSITIONS.TOP,
    staminaCost: 9,
    basePower: 78,
    description: 'Chain a leg lace out of a defended gut wrench',
    counters: ['hip_heist', 'granby_roll'],
    strongAgainst: ['base_build', 'short_sit', 'head_post'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'exposure', pinChance: 0.12 },
    flavor: 'Gut to lace - the women’s par terre signature.',
    styles: ['womens_freestyle'],
  },

  // ══ TOP TURNS / NEAR FALL ════════════════════════════════════════════════════

  half_nelson: {
    id: 'half_nelson',
    name: 'Half Nelson',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 7,
    basePower: 68,
    description: 'Drive under the arm to turn and expose the back',
    counters: ['hip_heist', 'granby_roll'],
    setupRequired: [CONDITIONS.BROKEN_DOWN],
    scoreEffect: { type: 'near_fall', pinChance: 0.18 },
    flavor: 'Under the arm - drive to the back!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  power_half: {
    id: 'power_half',
    name: 'Power Half',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 10,
    basePower: 82,
    description: 'Force the half nelson with full body leverage',
    counters: ['granby_roll'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.28 },
    flavor: 'All the power to the turn!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  near_side_cradle: {
    id: 'near_side_cradle',
    name: 'Near-Side Cradle',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 74,
    description: 'Lock near-side head and knee for a powerful pin threat',
    counters: ['hip_heist'],
    strongAgainst: ['short_sit'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.3 },
    flavor: 'Lock it up and squeeze!',
    styles: ['folkstyle', 'freestyle'],
  },
  arm_bar: {
    id: 'arm_bar',
    name: 'Arm Bar',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 74,
    description: 'Bar the arm behind the back and drive the turn',
    counters: ['hip_heist'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall' },
    flavor: 'Bar the arm, start the turn.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  far_side_tilt: {
    id: 'far_side_tilt',
    name: 'Far Side Tilt',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 7,
    basePower: 65,
    description: 'Reach the far side, tilt and hold for exposure',
    counters: ['granby_roll', 'sit_out'],
    setupRequired: [CONDITIONS.BROKEN_DOWN],
    scoreEffect: { type: 'near_fall' },
    flavor: 'Reach far, tilt and hold.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  crossface_cradle: {
    id: 'crossface_cradle',
    name: 'Crossface Cradle',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 72,
    description: 'From crossface pressure - lock the cradle for a near-fall',
    counters: ['hip_heist'],
    strongAgainst: ['short_sit'],
    setupRequired: [CONDITIONS.BROKEN_DOWN],
    scoreEffect: { type: 'near_fall', pinChance: 0.25 },
    flavor: 'Lock the cradle from the crossface!',
    styles: ['folkstyle', 'freestyle'],
  },
  tilt: {
    id: 'tilt',
    name: 'Tilt',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 76,
    description: 'Tilt and rotate to expose the back',
    counters: ['hip_heist', 'granby_roll'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall' },
    flavor: 'Expose the back.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  arm_turk: {
    id: 'arm_turk',
    name: 'Arm Turk',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 66,
    description: 'Hook the arm in a turk and drive to the back',
    counters: ['granby_roll'],
    setupRequired: [CONDITIONS.TOP_PRESSURE],
    scoreEffect: { type: 'near_fall', pinChance: 0.15 },
    flavor: 'Hook the arm, lock it down.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  leg_turk: {
    id: 'leg_turk',
    name: 'Leg Turk',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 68,
    description: 'Hook the leg in a turk and squeeze for the fall',
    counters: ['hip_heist'],
    setupRequired: [CONDITIONS.TOP_PRESSURE],
    scoreEffect: { type: 'near_fall', pinChance: 0.15 },
    flavor: 'Hook the leg, squeeze for the fall.',
    styles: ['folkstyle', 'freestyle'],
  },
  // Surfboard - step-over back-exposure punisher. Top-turn category, near-fall
  // scoring with a moderate pin chance comparable to half_nelson / power_half.
  surfboard: {
    id: 'surfboard',
    name: 'Surfboard',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 7,
    basePower: 64,
    description: 'Step over the back, pull both arms - punish exposure',
    counters: ['granby_roll', 'sit_out'],
    setupRequired: [CONDITIONS.TOP_PRESSURE],
    scoreEffect: { type: 'near_fall', pinChance: 0.18 },
    flavor: 'Paddle for the lights.',
    styles: ['folkstyle', 'freestyle'],
  },

  // ══ BOTTOM ESCAPES & REVERSALS ════════════════════════════════════════════════

  stand_up: {
    id: 'stand_up',
    name: 'Stand-Up',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 6,
    basePower: 50,
    description: 'Explode to your feet and fight the hands',
    counters: ['mat_return', 'spiral_ride'],
    strongAgainst: ['ankle_ride', 'pop_chop', 'tight_waist'],
    setupRequired: [],
    scoreEffect: { type: 'escape' },
    flavor: 'Base up and get to your feet!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  switch_move: {
    id: 'switch_move',
    name: 'Switch',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 60,
    description: 'Sit through, clear the arm, reverse position',
    counters: ['mat_return', 'spiral_ride', 'tight_waist'],
    strongAgainst: ['tight_waist', 'mat_return', 'ankle_ride'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Sit through and reverse!',
    styles: ['folkstyle', 'freestyle'],
  },
  sit_out: {
    id: 'sit_out',
    name: 'Sit-Out',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 6,
    basePower: 52,
    description: 'Sit out hard and turn in to face',
    counters: ['cross_face_pressure', 'spiral_ride'],
    strongAgainst: ['cross_face_pressure', 'claw_ride'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Sit through and turn!',
    styles: ['folkstyle', 'freestyle'],
  },
  short_sit: {
    id: 'short_sit',
    name: 'Short Sit',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 4,
    basePower: 70,
    description: 'Sit short to create space and set up',
    counters: ['tight_waist'],
    strongAgainst: ['tight_waist', 'power_half'],
    setupRequired: [],
    scoreEffect: { type: 'setup' },
    flavor: 'Sit short, create the angle.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  head_post: {
    id: 'head_post',
    name: 'Head Post',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 4,
    basePower: 70,
    description: 'Post the head to build separation',
    counters: ['spiral_ride'],
    strongAgainst: ['spiral_ride', 'cross_face_pressure'],
    setupRequired: [],
    scoreEffect: { type: 'setup' },
    flavor: 'Post the head, build the base.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  granby_roll: {
    id: 'granby_roll',
    name: 'Granby Roll',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 6,
    basePower: 66,
    description: 'Roll through the shoulder to escape or reverse',
    counters: ['tight_waist'],
    strongAgainst: [
      'half_nelson', 'power_half', 'far_side_tilt', 'arm_turk',
      // Leg-ride chain finishers - granby is the classic leg-ride escape
      'banana_split', 'spladle', 'leg_cradle', 'grapevine_power_half',
      'leg_ride_power_half',
    ],
    setupRequired: [],
    scoreEffect: { type: 'escape' },
    flavor: 'Shoulder roll to freedom!',
    styles: ['folkstyle', 'freestyle'],
  },
  // Bridge and turn - defensive bridge that flips into a reversal when
  // the top wrestler tries to drive for back exposure. Strong against
  // gut wrench and exposure attempts.
  bridge_and_turn: {
    id: 'bridge_and_turn',
    name: 'Bridge & Turn',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 6,
    basePower: 62,
    description: 'Bridge into the drive, then turn in for the reversal',
    counters: ['tight_waist'],
    strongAgainst: ['gut_wrench', 'leg_lace', 'gut_wrench_to_leg_lace', 'arm_drag_to_gut_wrench'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Bridge hard, turn in, reverse.',
    styles: ['freestyle', 'womens_freestyle'],
  },
  // Belly-down defense - flatten out to deny exposure points. Pure
  // defense, no scoring either way; breaks the hold and resets to a
  // base-built bottom position. Critical when caught in a turn sequence.
  belly_down_defense: {
    id: 'belly_down_defense',
    name: 'Belly Down',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 4,
    basePower: 70,
    description: 'Flatten out to deny exposure points - no score either way',
    counters: [],
    strongAgainst: ['gut_wrench', 'leg_lace', 'gut_wrench_to_leg_lace', 'step_over'],
    setupRequired: [],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Flatten out, deny the back.',
    styles: ['freestyle', 'womens_freestyle'],
  },
  hip_heist: {
    id: 'hip_heist',
    name: 'Hip Heist',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 6,
    basePower: 56,
    description: 'Swing hips to create an angle and escape',
    counters: ['claw_ride'],
    strongAgainst: ['claw_ride', 'near_side_cradle', 'tilt', 'arm_bar', 'leg_turk'],
    setupRequired: [],
    scoreEffect: { type: 'escape' },
    flavor: 'Swing the hips free!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  hand_control_escape: {
    id: 'hand_control_escape',
    name: 'Hand Control',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 4,
    basePower: 62,
    description: 'Strip the grips and work to improve position',
    counters: ['tight_waist'],
    strongAgainst: ['ankle_ride', 'tight_waist', 'cross_wrist_ride'],
    setupRequired: [],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Break the grip, create space.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  hold_position: {
    // Greco-only defensive bottom card. Real Greco bottom is intentionally
    // constrained (no leg attacks, no re-shots, almost no offense) - the
    // smart strategy is to defend until the par-terre countdown expires
    // and the action resets to neutral. This card is the explicit way to
    // run that clock: low stamina cost, low power, sets GOOD_BASE so the
    // top wrestler's gut wrench probability drops.
    id: 'hold_position',
    name: 'Hold Position',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 3,
    basePower: 50,
    description: 'Stay heavy and posted - run the par-terre clock',
    counters: [],
    strongAgainst: ['gut_wrench', 'leg_lace'],
    setupRequired: [],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Heavy hips, broken grips. Wait them out.',
    styles: ['greco'],
  },
  belly_down: {
    id: 'belly_down',
    name: 'Belly Down',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 5,
    basePower: 80,
    description: 'Roll to the belly to stop exposure',
    counters: ['spiral_ride'],
    strongAgainst: ['tilt', 'far_side_tilt', 'arm_bar', 'arm_turk', 'leg_turk'],
    setupRequired: [],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Get to your belly!',
    styles: ['freestyle', 'greco'],
  },
  base_build: {
    id: 'base_build',
    name: 'Build a Base',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 3,
    basePower: 76,
    description: 'Get to base and build your platform',
    counters: ['pop_chop'],
    strongAgainst: ['pop_chop', 'spiral_ride', 'near_side_cradle', 'crossface_cradle'],
    setupRequired: [],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.BASE_BUILT },
    flavor: 'Get to base. Everything starts here.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  tripod_stand: {
    id: 'tripod_stand',
    name: 'Tripod Stand',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 48,
    description: 'Post hands and feet, push up to standing - powerful escape',
    counters: ['spiral_ride', 'mat_return'],
    setupRequired: [],
    scoreEffect: { type: 'escape' },
    flavor: 'Post up and break free!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ FREESTYLE BOTTOM OFFENSE (Freestyle only) ═══════════════════════════════

  re_shot_from_bottom: {
    id: 're_shot_from_bottom',
    name: 'Re-Shot (Bottom)',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 82,
    description: 'Grab a leg from bottom, roll through to top',
    counters: ['mat_return'],
    strongAgainst: ['tight_waist', 'spiral_ride'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Attack from bottom - grab the leg!',
    styles: ['freestyle'],
  },
  roll_through_attack: {
    id: 'roll_through_attack',
    name: 'Roll-Through',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 80,
    description: 'Snatch a leg, roll through for reversal',
    counters: ['mat_return', 'spiral_ride'],
    strongAgainst: ['tight_waist', 'mat_return'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Snatch the leg, roll through!',
    styles: ['freestyle'],
  },

  // ══ TIE-UP SETUP (Chain Wrestling Entry) ════════════════════════════════════

  collar_tie: {
    id: 'collar_tie',
    name: 'Collar Tie',
    category: 'transition',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 58,
    description: 'Grab the collar tie and control the head',
    counters: ['peek_out'],
    strongAgainst: ['re_shot', 'peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.TIE_UP },
    flavor: 'Grab the neck, control the dance.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  underhook_control: {
    id: 'underhook_control',
    name: 'Underhook',
    category: 'transition',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 60,
    description: 'Fight for the underhook to own inside position',
    counters: ['whizzer'],
    strongAgainst: ['stuff_head', 'whizzer'],
    setupRequired: [],
    scoreEffect: { type: 'setup', setsCondition: CONDITIONS.TIE_UP },
    flavor: 'Win the tie, win the match.',
    styles: ['folkstyle', 'freestyle'],
  },

  // ── SNAP DOWN (standalone - leads to front headlock from neutral) ──────────

  snap_down: {
    id: 'snap_down',
    name: 'Snap Down',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Snap head down hard - opens the front headlock',
    counters: ['peek_out'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.FRONT_HEADLOCK_CONTROL },
    flavor: 'Snap and lock it up!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ── TIE-UP FOLLOW-UPS (require TIE_UP condition) ─────────────────────────
  inside_trip: {
    id: 'inside_trip',
    name: 'Inside Trip',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 66,
    description: 'Hook the inside leg and trip to the mat from the tie-up',
    counters: ['whizzer', 'sprawl'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Hook the leg, take them down!',
    // Inside-leg trip = leg attack, illegal in Greco-Roman.
    styles: ['folkstyle', 'freestyle'],
  },
  drag_by: {
    id: 'drag_by',
    name: 'Drag By',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Drag the arm past you and spin behind from the tie-up',
    counters: ['whizzer'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Pull and spin - get behind!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  slide_by: {
    id: 'slide_by',
    name: 'Slide By',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Slide past the collar tie and get behind for a takedown',
    counters: ['sprawl'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Slide past and spin behind!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  // Foot Sweep - quick low-cost tie-up follow-up takedown. Sits between
  // sweep_single (62) and slide_by (64) in power; cheapest in the tie-up chain.
  foot_sweep: {
    id: 'foot_sweep',
    name: 'Foot Sweep',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 60,
    description: 'Sweep the lead leg from the outside, drop opponent flat',
    counters: ['sprawl'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Sweep the lead leg!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  // Cow Catcher - high-power tie-up combo: trap the arm, pick the leg.
  // Highest basePower in the tie-up chain (76); higher stamina cost reflects
  // the multi-grip commitment.
  cow_catcher: {
    id: 'cow_catcher',
    name: 'Cow Catcher',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 76,
    description: 'Trap the arm, pick the leg in one motion',
    counters: ['sprawl', 'whizzer'],
    setupRequired: [CONDITIONS.TIE_UP],
    scoreEffect: { type: 'takedown' },
    flavor: 'Arm trapped, leg captured!',
    styles: ['folkstyle', 'freestyle'],
  },

  // ══ HAND FIGHTING FOLLOW-UPS (require HAND_FIGHTING) ═══════════════════════

  hand_fight_snap: {
    id: 'hand_fight_snap',
    name: 'Hand Fight Snap',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Win the hand fight and snap down for a go-behind',
    counters: ['peek_out'],
    setupRequired: [CONDITIONS.HAND_FIGHTING],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.REAR_STANDING },
    flavor: 'Win the hands, control the head.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  hand_fight_reattack: {
    id: 'hand_fight_reattack',
    name: 'Hand Fight Re-Attack',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 56,
    description: 'Win the hand fight and re-attack for the takedown',
    counters: ['sprawl'],
    setupRequired: [CONDITIONS.HAND_FIGHTING],
    scoreEffect: { type: 'takedown' },
    flavor: 'Hands won, attack now!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ REAR STANDING FINISHERS (require REAR_STANDING) ═════════════════════════

  rear_mat_return: {
    id: 'rear_mat_return',
    name: 'Mat Return',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 68,
    description: 'Return to the mat from behind for the finish',
    counters: ['sit_out', 'switch_move'],
    setupRequired: [CONDITIONS.REAR_STANDING],
    scoreEffect: { type: 'takedown' },
    flavor: 'Drive them to the mat!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  rear_trip: {
    id: 'rear_trip',
    name: 'Rear Trip',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 7,
    basePower: 70,
    description: 'Trip the leg from behind for a quick takedown',
    counters: ['granby_roll'],
    setupRequired: [CONDITIONS.REAR_STANDING],
    scoreEffect: { type: 'takedown' },
    flavor: 'Hook the leg and trip!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  rear_lift: {
    id: 'rear_lift',
    name: 'Rear Lift',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 8,
    basePower: 72,
    description: 'Lift and return to mat with authority',
    counters: ['switch_move'],
    setupRequired: [CONDITIONS.REAR_STANDING],
    scoreEffect: { type: 'takedown' },
    flavor: 'Lift them off their feet!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },


  // ══ SCRAMBLE CARDS (require SCRAMBLE condition) ═════════════════════════════

  scramble_reattack: {
    id: 'scramble_reattack',
    name: 'Scramble Re-Attack',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 6,
    basePower: 66,
    description: 'Keep attacking through the scramble',
    counters: [],
    setupRequired: [CONDITIONS.SCRAMBLE],
    scoreEffect: { type: 'takedown' },
    flavor: 'Stay on the attack!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  scramble_come_out_top: {
    id: 'scramble_come_out_top',
    name: 'Come Out On Top',
    category: 'neutral_attack',
    position: POSITIONS.NEUTRAL,
    staminaCost: 5,
    basePower: 64,
    description: 'Fight through and come out on top',
    counters: [],
    setupRequired: [CONDITIONS.SCRAMBLE],
    scoreEffect: { type: 'takedown' },
    flavor: 'Scramble hard - come out on top!',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },
  scramble_clear_hips: {
    id: 'scramble_clear_hips',
    name: 'Clear Hips',
    category: 'neutral_counter',
    position: POSITIONS.NEUTRAL,
    staminaCost: 4,
    basePower: 62,
    description: 'Clear the hips and get back to neutral',
    counters: [],
    setupRequired: [CONDITIONS.SCRAMBLE],
    scoreEffect: { type: 'counter' },
    flavor: 'Hips free - back to neutral.',
    styles: ['folkstyle', 'freestyle', 'greco'],
  },

  // ══ LEG RIDE SETUP + CHAIN (Folkstyle) ══════════════════════════════════════

  get_legs_in: {
    id: 'get_legs_in',
    name: 'Get Legs In',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 6,
    basePower: 64,
    description: 'Hook your legs inside theirs to lock in the ride',
    counters: ['belly_down', 'granby_roll'],
    // No prerequisite - leg ride is a base top-position option, not a
    // chain-only finisher. When CONTROL_ESTABLISHED is set, the chain
    // bonus (see CHAIN_SEQUENCES in wrestlingEngine.js) lifts the
    // success rate to reward setting up a base first.
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.LEG_RIDE_ESTABLISHED },
    flavor: 'Legs in - now nobody\'s going anywhere.',
    styles: ['folkstyle'],
  },
  grapevine_power_half: {
    id: 'grapevine_power_half',
    name: 'Grapevine Power Half',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 10,
    basePower: 86,
    description: 'Grapevine both legs and crank the power half for the turn',
    counters: ['granby_roll', 'belly_down'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.34 },
    flavor: 'Legs wrapped, half cranking - turn him!',
    styles: ['folkstyle'],
  },
  cross_body_ride: {
    id: 'cross_body_ride',
    name: 'Cross-Body Ride',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 70,
    description: 'Drape across the body with a leg hooked - pressure to the turn',
    counters: ['cross_body_defense', 'hip_heist'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.2 },
    flavor: 'Perpendicular pressure - crush him flat.',
    styles: ['folkstyle'],
  },
  saturday_night_ride: {
    id: 'saturday_night_ride',
    name: 'Saturday Night Ride',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 72,
    description: 'Over-under leg hook combo that scrambles the base',
    counters: ['cross_body_defense', 'hip_heist'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.24 },
    flavor: 'Saturday night, lights on - ride to the back.',
    styles: ['folkstyle'],
  },
  leg_cradle: {
    id: 'leg_cradle',
    name: 'Leg Cradle',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 9,
    basePower: 80,
    description: 'Trap the head and knee with legs in for a deep cradle',
    counters: ['hip_heist', 'short_sit'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.3 },
    flavor: 'Head and knee - lock it and squeeze.',
    styles: ['folkstyle'],
  },
  leg_ride_power_half: {
    id: 'leg_ride_power_half',
    name: 'Leg Ride Power Half',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 10,
    basePower: 86,
    description: 'Power half with legs locked in - the bottom man has no base to fight back',
    counters: ['granby_roll', 'belly_down'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.34 },
    flavor: 'Legs locked, half cranking - backs flat.',
    styles: ['folkstyle'],
  },
  banana_split: {
    id: 'banana_split',
    name: 'Banana Split',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 12,
    basePower: 88,
    description: 'Spread the legs wide into a painful exposure - the classic leg-ride finisher',
    counters: ['granby_roll', 'belly_down', 'cross_body_defense'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.36 },
    flavor: 'Split it open - back points on the way.',
    styles: ['folkstyle'],
  },
  spladle: {
    id: 'spladle',
    name: 'Spladle',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 11,
    basePower: 86,
    description: 'Roll through the leg ride into a straddle pin combination',
    counters: ['granby_roll', 'belly_down'],
    setupRequired: [CONDITIONS.LEG_RIDE_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.34 },
    flavor: 'Roll through - backs flat, pin on.',
    styles: ['folkstyle'],
  },

  // ══ ADDITIONAL TOP RIDES & TURNS (Folkstyle v2) ═════════════════════════════

  navy_ride: {
    id: 'navy_ride',
    name: 'Navy Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 62,
    description: 'Control ride setup - one leg in, hand on the ankle',
    counters: ['stand_up', 'tripod_stand', 'belly_down'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.TOP_PRESSURE },
    flavor: 'One leg in - set up the turn.',
    styles: ['folkstyle'],
  },
  wrist_ride: {
    id: 'wrist_ride',
    name: 'Wrist Ride',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 62,
    description: 'Control the wrist and drive forward to break him down',
    counters: ['hand_control_escape', 'stand_up'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.CONTROL_ESTABLISHED },
    flavor: 'Own the wrist - own the man.',
    styles: ['folkstyle'],
  },
  tight_waist_chop: {
    id: 'tight_waist_chop',
    name: 'Tight Waist & Chop',
    category: 'transition',
    position: POSITIONS.TOP,
    staminaCost: 5,
    basePower: 62,
    description: 'Tight waist with a chop to the arm to break him down flat',
    counters: ['short_sit', 'hip_heist'],
    setupRequired: [],
    scoreEffect: { type: 'control', setsCondition: CONDITIONS.BROKEN_DOWN },
    flavor: 'Chop the post - flatten him out.',
    styles: ['folkstyle'],
  },
  chicken_wing: {
    id: 'chicken_wing',
    name: 'Chicken Wing',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 8,
    basePower: 78,
    description: 'Trap the arm high and lever the turn - bottom man\'s shoulder is in trouble',
    counters: ['hip_heist', 'granby_roll', 'peterson_roll'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.26 },
    flavor: 'Wing it high - back points incoming.',
    styles: ['folkstyle'],
  },
  double_arm_bar: {
    id: 'double_arm_bar',
    name: 'Double Arm Bar',
    category: 'top_turns',
    position: POSITIONS.TOP,
    staminaCost: 9,
    basePower: 82,
    description: 'Bar both arms behind the back - nowhere to post, nowhere to go',
    counters: ['hip_heist', 'granby_roll', 'peterson_roll', 'wing_roll'],
    setupRequired: [CONDITIONS.CONTROL_ESTABLISHED],
    scoreEffect: { type: 'near_fall', pinChance: 0.3 },
    flavor: 'Both arms barred - lock the turn.',
    styles: ['folkstyle'],
  },

  // ══ ADDITIONAL BOTTOM ESCAPES & REVERSALS (Folkstyle v2) ════════════════════

  peterson_roll: {
    id: 'peterson_roll',
    name: 'Peterson Roll',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 64,
    description: 'Classic counter to a half nelson - roll him through for 2',
    counters: ['cross_face_pressure', 'spiral_ride'],
    strongAgainst: ['half_nelson', 'chicken_wing'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Peterson! Rolled him clean.',
    styles: ['folkstyle'],
  },
  wing_roll: {
    id: 'wing_roll',
    name: 'Wing Roll',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 62,
    description: 'Counter to arm bar / chicken wing - roll through the trapped arm',
    counters: ['tight_waist', 'mat_return_from_leg'],
    strongAgainst: ['arm_bar', 'chicken_wing', 'double_arm_bar'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Roll the wing - he goes with you.',
    styles: ['folkstyle'],
  },
  fake_switch_to_granby: {
    id: 'fake_switch_to_granby',
    name: 'Fake Switch to Granby',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 9,
    basePower: 70,
    description: 'Fake the switch to draw pressure, then shoot the granby underneath',
    counters: ['cross_face_pressure', 'claw_ride'],
    strongAgainst: ['tight_waist', 'pop_chop'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Show the switch - hit the granby.',
    styles: ['folkstyle'],
  },
  granby_to_peterson: {
    id: 'granby_to_peterson',
    name: 'Granby to Peterson',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 9,
    basePower: 72,
    description: 'Granby roll into a Peterson - double the motion, double the reversal',
    counters: ['cross_face_pressure', 'claw_ride'],
    strongAgainst: ['half_nelson', 'power_half'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Granby to Peterson - two moves, one reversal.',
    styles: ['folkstyle'],
  },
  sit_out_turn_in: {
    id: 'sit_out_turn_in',
    name: 'Sit-Out Turn-In',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 7,
    basePower: 66,
    description: 'Sit out and immediately turn in to face the top man for the reversal',
    counters: ['cross_face_pressure'],
    setupRequired: [CONDITIONS.GOOD_BASE],
    scoreEffect: { type: 'reversal' },
    flavor: 'Sit out, turn in - back on the attack.',
    styles: ['folkstyle'],
  },
  short_offense_switch: {
    id: 'short_offense_switch',
    name: 'Short-Offense Switch',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 8,
    basePower: 68,
    description: 'Tight short-offense switch - low and quick under the arm',
    counters: ['tight_waist', 'spiral_ride'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Short switch - in and under.',
    styles: ['folkstyle'],
  },
  reverse_switch: {
    id: 'reverse_switch',
    name: 'Reverse Switch',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 8,
    basePower: 70,
    description: 'Switch in the opposite direction - catches them leaning the wrong way',
    counters: ['tight_waist', 'spiral_ride'],
    setupRequired: [CONDITIONS.GOOD_BASE],
    scoreEffect: { type: 'reversal' },
    flavor: 'Other way! Reverse switch.',
    styles: ['folkstyle'],
  },
  outside_roll: {
    id: 'outside_roll',
    name: 'Outside Roll',
    category: 'bottom',
    position: POSITIONS.BOTTOM,
    staminaCost: 8,
    basePower: 66,
    description: 'Roll to the outside when they ride too heavy on one side',
    counters: ['claw_ride', 'two_on_one_ride'],
    setupRequired: [],
    scoreEffect: { type: 'reversal' },
    flavor: 'Too heavy - roll him off.',
    styles: ['folkstyle'],
  },
  cross_body_defense: {
    id: 'cross_body_defense',
    name: 'Cross-Body Defense',
    category: 'transition',
    position: POSITIONS.BOTTOM,
    staminaCost: 5,
    basePower: 72,
    description: 'Defend against cross-body rides and leg hooks - clear the legs out',
    counters: [],
    strongAgainst: ['cross_body_ride', 'saturday_night_ride', 'navy_ride'],
    setupRequired: [],
    scoreEffect: { type: 'defense', setsCondition: CONDITIONS.GOOD_BASE },
    flavor: 'Clear the leg - stop the ride.',
    styles: ['folkstyle'],
  },
};

// ─── Utility ──────────────────────────────────────────────────────────────────

// Neutral attack cards that make no sense while trapped in a front headlock
const FHL_TRAPPED_EXCLUDED_IDS = new Set([
  'double_leg', 'single_leg', 'high_crotch', 'sweep_single', 'duck_under',
  'snap_spin', 'go_behind', 'arm_drag', 'fireman_carry', 're_shot',
  'stuff_head', 'down_block', 'whizzer', 'sprawl',
  'suplex', 'headlock_throw', 'lateral_drop', 'bear_hug_lift',
  // Greco-specific
  'pummel_inside', 'arm_throw', 'shuck_by',
  // Tie-up/chain cards
  'collar_tie', 'underhook_control', 'snap_down', 'inside_trip', 'drag_by', 'slide_by', 'duck_under',
]);

// When TIE_UP is active, these shot-based neutral cards are excluded
const TIE_UP_EXCLUDED_IDS = new Set([
  'double_leg', 'single_leg', 'high_crotch', 'sweep_single',
]);

// When LEG_ATTACK_SECURED is active, these neutral cards don't fit - you have a leg
const LEG_ATTACK_EXCLUDED_IDS = new Set([
  'collar_tie', 'underhook_control', 'snap_down', 'snap_spin',
  'go_behind', 'arm_drag', 're_shot', 'stuff_head', 'down_block',
  'pummel_inside', 'arm_throw', 'shuck_by',
]);

// When FRONT_HEADLOCK_CONTROL is active, only FHL branch cards make sense - exclude everything else
const FHL_CONTROL_EXCLUDED_IDS = new Set([
  'collar_tie', 'underhook_control',  // can't re-enter setup from FHL
  'whizzer', 'sprawl', 'down_block', 'stuff_head', // shot defenses, irrelevant from FHL
  'double_leg', 'single_leg', 'high_crotch', 'sweep_single', 'fireman_carry', // can't shoot from FHL
  'duck_under', 'slide_by', 'drag_by', 'snap_spin', // neutral attacks incompatible with FHL
  'arm_drag', 'go_behind', 're_shot', // you already have control
  'peek_out', // peek_out is for escaping FHL, not attacking from it
  // Greco-specific
  'pummel_inside', 'arm_throw', 'shuck_by',
  'suplex', 'headlock_throw', 'lateral_drop', 'bear_hug_lift',
]);

// When REAR_STANDING is active, these neutral cards don't fit - you're already behind them.
// headlock_throw needs front head control and lateral_drop needs a front over-under tie;
// neither works from behind. A belly-to-back suplex and rear body-lock lift do, so those stay.
const REAR_STANDING_EXCLUDED_IDS = new Set([
  'double_leg', 'single_leg', 'high_crotch', 'sweep_single',
  'collar_tie', 'underhook_control', 'snap_down', 'snap_spin',
  'fireman_carry', 're_shot', 'stuff_head', 'down_block',
  'headlock_throw', 'lateral_drop',
]);

// When LEG_RIDE_ESTABLISHED is active, you have legs hooked in - only leg-chain finishers + generic control moves fit.
// Exclude other top turns/rides that assume a different hold.
const LEG_RIDE_EXCLUDED_IDS = new Set([
  'get_legs_in', // can't re-establish the ride you already have
  'spiral_ride', 'ankle_ride', 'claw_ride', 'cross_wrist_ride', // alternative rides incompatible with legs-in
  'navy_ride', 'wrist_ride', 'tight_waist_chop', 'tight_waist', 'spiral_breakdown',
  'head_post', 'cross_face_pressure', 'pop_chop', 'chop_and_drive',
  'two_on_one_ride', // alternate ride setup
  // Standard turns that don't chain off legs specifically (leg-ride chain cards are preferred)
  'chicken_wing', 'double_arm_bar', 'bar_arm',
]);

export function getAvailableCards(position, conditions = [], style = 'folkstyle') {
  const isFhlTrapped = conditions.includes(CONDITIONS.FRONT_HEADLOCK_TRAPPED);
  const isLegTrapped = conditions.includes(CONDITIONS.LEG_ATTACK_TRAPPED);
  const isFhlControl = conditions.includes(CONDITIONS.FRONT_HEADLOCK_CONTROL);
  const isTieUp = conditions.includes(CONDITIONS.TIE_UP);
  const isRearStanding = conditions.includes(CONDITIONS.REAR_STANDING);
  const isRearTrapped = conditions.includes(CONDITIONS.REAR_STANDING_TRAPPED);
  const isLegAttack = conditions.includes(CONDITIONS.LEG_ATTACK_SECURED);
  const isLegRide = conditions.includes(CONDITIONS.LEG_RIDE_ESTABLISHED);

  // Women's freestyle uses the men's freestyle card pool by default. Cards
  // tagged 'womens_freestyle' (women's-specific signature moves) are also
  // included. When tuning women's mode further, cards can opt out of the
  // freestyle pool by tagging only ['womens_freestyle'].
  const styleMatches = (cardStyles) => {
    if (!cardStyles) return true;
    if (cardStyles.includes(style)) return true;
    if (style === 'womens_freestyle' && cardStyles.includes('freestyle')) return true;
    return false;
  };

  return Object.values(CARDS).filter(card => {
    // Style filter - only show cards that belong to this wrestling style
    if (!styleMatches(card.styles)) return false;

    // Trapped-state pools are resolved BEFORE the position filter. A trapped
    // wrestler is restricted to their dedicated defense pool regardless of the
    // `position` field: the defense cards are position:NEUTRAL, and a stale or
    // mismatched position must never empty the pool (which would fall back to
    // unrelated neutral cards). Style is already applied above.
    // When trapped in a front headlock, only FHL defense cards and peek_out are available
    if (isFhlTrapped) {
      return card.fhlDefense === true || card.id === 'peek_out';
    }

    // When trapped in a leg attack, only the dedicated leg-defense pool is
    // available. Six cards: limp_leg, whizzer_hop, crossface_and_circle,
    // front_headlock_counter, whizzer_lateral_drop, heavy_hips.
    if (isLegTrapped) {
      return card.legDefense === true;
    }

    // When trapped in a rear standing position, only the dedicated rear-defense
    // pool is available (rear_hand_fight, rear_hip_down, rear_whizzer_block,
    // and folkstyle-only rear_standing_switch / rear_peel_and_turn).
    if (isRearTrapped) {
      return card.rearDefense === true;
    }

    if (card.position !== null && card.position !== position) return false;

    // Exclude FHL defense cards unless the player has FRONT_HEADLOCK_TRAPPED
    if (card.fhlDefense === true) return false;

    // Exclude leg defense cards unless the player has LEG_ATTACK_TRAPPED
    if (card.legDefense === true) return false;

    // Exclude rear-defense cards unless the player has REAR_STANDING_TRAPPED
    if (card.rearDefense === true) return false;

    // Peek out only available when trapped in FHL or in a tie-up. Leg-trapped
    // has its own dedicated 6-card pool (limp_leg, whizzer_hop, crossface_and_circle,
    // front_headlock_counter, whizzer_lateral_drop, heavy_hips) so peek_out is
    // redundant filler there.
    if (card.id === 'peek_out' && !isFhlTrapped && !isTieUp) return false;

    // When controlling a front headlock, only FHL branch cards + snap_down are relevant
    if (isFhlControl && FHL_CONTROL_EXCLUDED_IDS.has(card.id)) return false;

    // When the leg ride is established, only leg-chain finishers make sense from TOP
    if (isLegRide && LEG_RIDE_EXCLUDED_IDS.has(card.id)) return false;
    if (isLegRide && card.scoreEffect?.setsCondition === CONDITIONS.LEG_RIDE_ESTABLISHED) return false;

    // When in a tie-up, hide cards that SET TIE_UP (can't re-enter collar tie)
    if (isTieUp && card.scoreEffect?.setsCondition === CONDITIONS.TIE_UP) return false;

    // When leg attack secured, exclude incompatible neutral attacks - you have a leg
    if (isLegAttack && LEG_ATTACK_EXCLUDED_IDS.has(card.id)) return false;
    if (isLegAttack && card.scoreEffect?.setsCondition === CONDITIONS.LEG_ATTACK_SECURED) return false;
    // Can't throw for amplitude or re-tie while one of their legs is in your hands
    if (isLegAttack && card.scoreEffect?.type === 'grand_amplitude') return false;
    if (isLegAttack && card.scoreEffect?.setsCondition === CONDITIONS.TIE_UP) return false;

    // When in rear standing, exclude incompatible neutral attacks
    if (isRearStanding && REAR_STANDING_EXCLUDED_IDS.has(card.id)) return false;
    if (isRearStanding && card.scoreEffect?.setsCondition === CONDITIONS.TIE_UP) return false;
    if (isRearStanding && card.scoreEffect?.setsCondition === CONDITIONS.REAR_STANDING) return false;

    // When in a tie-up, exclude shot-based takedowns that don't fit
    if (isTieUp && TIE_UP_EXCLUDED_IDS.has(card.id)) return false;

    if (card.setupRequired && card.setupRequired.length > 0) {
      return card.setupRequired.every(req => conditions.includes(req));
    }
    return true;
  });
}

export function getCardById(id) {
  return CARDS[id] || null;
}
